name: Build And Put Static Files
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  AWS_REGION: ap-northeast-1
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/kagari-ecr-image-pusher
          aws-region: ${{env.AWS_REGION}}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: push static file to s3
        run: aws s3 sync ./dist s3://kagari-frontend-static --delete --storage-class STANDARD_IA
